modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="magitech_era_resources"
version="1.0.0"
displayName="Magitech Era Resources"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Felix, MCreator"
description="Assets and resources for the Magitech Era modpack."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.magitech_era_resources]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration